version: "3"
services:
  app:
    build: .
    image: hendriam18/bookstore-api
    container_name: bookstore-api
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRED=${JWT_EXPIRED}
      - LEVEL_LOG=${LEVEL_LOG}
      - REDIS_URL=${REDIS_URL}
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
networks:
  default:
    external: true
    name: local
