version: "3"
services:
  app-server:
    build: .
    image: hendriam18/bookstore:v1
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo-server:27017/bookstore
      - JWT_SECRET=ccee94dea3077d9f7fff8d00ddf3afe3ce747e5f1b388f661b698cddeaca4e98
      - JWT_EXPIRED=1d
      - LEVEL_LOG=info
      - REDIS_URL=redis://redis-server:6379
    expose:
      - 3000
    ports:
      - 3000:3000
  mongo-server:
    image: mongo:8.0
    ports:
      - '27017:27017'
  redis-server:
    image: redis:latest
    ports:
      - '6379:6379'
networks:
  default:
    external: true
    name: local
