version: "3"
services:
  app-server:
    build: .
    image: hendriam18/bookstore:v1
    env_file:
      - .env
    ports:
      - 3000:3000
  mongo-server:
    image: mongo:8.0
    ports:
      - '27017:27017'
  redis-server:
    image: redis:latest
    ports:
      - '6379:6379'
networks:
  default:
    external: true
    name: local
